version: '2.17.2'

services:
  api:
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: tail -f /dev/null
    networks:
      - gapps
    ports:
      - "4567:4567"
    volumes:
      - ./:/api
    working_dir: /api

networks:
  gapps:
    driver: bridge
